package xmptype_test

// Port of org.apache.xmpbox.type.TestStructuredType, over the same thirty-one
// rows its initializeParameters declares.
//
// Java drives it entirely by reflection: it names a getter and a setter by
// capitalising the field name, calls them with Class.getMethod, and asks
// type.getImplementingClass() what class the stored property should be. Go has
// no reflection the port uses, so each row names its own accessors. The four
// questions the Java asks are the four asked here:
//
//   - testInitializedToNull: a fresh value has nothing for the field, and the
//     accessor answers Java's null.
//   - testSettingValue: setting one field leaves every other one unset.
//   - testPropertyType: the property stored is of the class the Types constant
//     names.
//   - testSetter: the setter stores the value and the getter gives it back.
//
// The two random variants -- testRandomSettingValue and testRandomSetter --
// re-run the same body fifty times with a fresh Random, which tests the
// accessors rather than the values; they add nothing once the value is not
// generated by reflection, and are recorded as dropped in migration/STATUS.md.
//
// AbstractTypeTester.getJavaValue makes a "Text_String_<random>" for a text
// type, a Calendar of a random epoch for a date and a random int for an
// integer. The port uses one fixed value of each shape instead, for the reason
// above.

import (
	"testing"
	"time"

	"github.com/shinguakira/pdfbox-go/go/xmpbox"
	"github.com/shinguakira/pdfbox-go/go/xmpbox/xmptype"
)

// The three values the port uses where Java generates a random one.
var (
	testTextValue    = "Text_String_1"
	testDateValue    = time.Date(2010, 3, 22, 14, 33, 11, 0, time.UTC)
	testIntegerValue = 42
)

// structuredRow is one row of Java's initializeParameters, with the accessors
// its reflection would have found.
type structuredRow struct {
	// owner names the structured type, for the failure message.
	owner string

	// fieldName is the field being exercised.
	fieldName string

	// typeName is the Java class the stored property should have, which is
	// type.getImplementingClass().
	typeName string

	// value is the value to set, of the shape getJavaValue makes for the type.
	value any

	// make returns a fresh value of the structured type, with the names of
	// every field it declares.
	make func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string)

	// get reads the field back through the type's own accessor, and answers
	// false where the accessor says Java's null.
	get func(s xmptype.AbstractStructuredType) (any, bool)

	// set writes the field through the type's own accessor.
	set func(s xmptype.AbstractStructuredType, value any) error
}

// jobFields and the six beside it are the fields each type declares, which Java
// finds with getXmpFields.
var (
	jobFields = []string{xmptype.JobID, xmptype.JobName, xmptype.JobURL}

	layerFields = []string{xmptype.LayerLayerName, xmptype.LayerLayerText}

	resourceEventFields = []string{
		xmptype.ResourceEventAction, xmptype.ResourceEventChanged,
		xmptype.ResourceEventInstanceID, xmptype.ResourceEventParameters,
		xmptype.ResourceEventSoftwareAgent, xmptype.ResourceEventWhen,
	}

	resourceRefFields = []string{
		xmptype.ResourceRefDocumentID, xmptype.ResourceRefFilePath,
		xmptype.ResourceRefInstanceID, xmptype.ResourceRefLastModifyDate,
		xmptype.ResourceRefManageTo, xmptype.ResourceRefManageUI,
		xmptype.ResourceRefManager, xmptype.ResourceRefManagerVariant,
		xmptype.ResourceRefPartMapping, xmptype.ResourceRefRenditionParams,
		xmptype.ResourceRefVersionID, xmptype.ResourceRefMaskMarkers,
		xmptype.ResourceRefRenditionClass, xmptype.ResourceRefFromPart,
		xmptype.ResourceRefToPart,
	}

	thumbnailFields = []string{
		xmptype.ThumbnailFormat, xmptype.ThumbnailHeight,
		xmptype.ThumbnailWidth, xmptype.ThumbnailImage,
	}

	versionFields = []string{
		xmptype.VersionComments, xmptype.VersionEvent, xmptype.VersionModifier,
		xmptype.VersionModifyDate, xmptype.VersionVersion,
	}
)

// stringGetter turns a typed accessor into the shape structuredRow wants, where
// the empty string is Java's null.
func stringGetter[T xmptype.AbstractStructuredType](read func(T) string) func(
	xmptype.AbstractStructuredType) (any, bool) {
	return func(s xmptype.AbstractStructuredType) (any, bool) {
		value := read(s.(T))
		return value, value != ""
	}
}

// stringSetter turns a typed setter into the shape structuredRow wants.
func stringSetter[T xmptype.AbstractStructuredType](write func(T, string) error) func(
	xmptype.AbstractStructuredType, any) error {
	return func(s xmptype.AbstractStructuredType, value any) error {
		return write(s.(T), value.(string))
	}
}

// structuredRows is Java's initializeParameters.
func structuredRows() []structuredRow {
	job := func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string) {
		return xmptype.NewJobTypePrefixed(m, "job"), jobFields
	}
	layer := func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string) {
		return xmptype.NewLayerType(m), layerFields
	}
	event := func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string) {
		return xmptype.NewResourceEventType(m), resourceEventFields
	}
	ref := func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string) {
		return xmptype.NewResourceRefType(m), resourceRefFields
	}
	thumbnail := func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string) {
		return xmptype.NewThumbnailType(m), thumbnailFields
	}
	version := func(m xmptype.MetadataLike) (xmptype.AbstractStructuredType, []string) {
		return xmptype.NewVersionType(m), versionFields
	}

	return []structuredRow{
		// data for JobType
		{"JobType", xmptype.JobID, "TextType", testTextValue, job,
			stringGetter(func(j *xmptype.JobType) string { return j.ID() }),
			stringSetter(func(j *xmptype.JobType, v string) error { return j.SetID(v) })},
		{"JobType", xmptype.JobName, "TextType", testTextValue, job,
			stringGetter(func(j *xmptype.JobType) string { return j.Name() }),
			stringSetter(func(j *xmptype.JobType, v string) error { return j.SetName(v) })},
		{"JobType", xmptype.JobURL, "URLType", testTextValue, job,
			stringGetter(func(j *xmptype.JobType) string { return j.URL() }),
			stringSetter(func(j *xmptype.JobType, v string) error { return j.SetURL(v) })},

		// data for LayerType
		{"LayerType", xmptype.LayerLayerName, "TextType", testTextValue, layer,
			stringGetter(func(l *xmptype.LayerType) string { return l.LayerName() }),
			stringSetter(func(l *xmptype.LayerType, v string) error { return l.SetLayerName(v) })},
		{"LayerType", xmptype.LayerLayerText, "TextType", testTextValue, layer,
			stringGetter(func(l *xmptype.LayerType) string { return l.LayerText() }),
			stringSetter(func(l *xmptype.LayerType, v string) error { return l.SetLayerText(v) })},

		// data for ResourceEventType
		{"ResourceEventType", xmptype.ResourceEventAction, "ChoiceType", testTextValue, event,
			stringGetter(func(e *xmptype.ResourceEventType) string { return e.Action() }),
			stringSetter(func(e *xmptype.ResourceEventType, v string) error { return e.SetAction(v) })},
		{"ResourceEventType", xmptype.ResourceEventChanged, "TextType", testTextValue, event,
			stringGetter(func(e *xmptype.ResourceEventType) string { return e.Changed() }),
			stringSetter(func(e *xmptype.ResourceEventType, v string) error { return e.SetChanged(v) })},
		{"ResourceEventType", xmptype.ResourceEventInstanceID, "GUIDType", testTextValue, event,
			stringGetter(func(e *xmptype.ResourceEventType) string { return e.InstanceID() }),
			stringSetter(func(e *xmptype.ResourceEventType, v string) error { return e.SetInstanceID(v) })},
		{"ResourceEventType", xmptype.ResourceEventParameters, "TextType", testTextValue, event,
			stringGetter(func(e *xmptype.ResourceEventType) string { return e.Parameters() }),
			stringSetter(func(e *xmptype.ResourceEventType, v string) error { return e.SetParameters(v) })},
		{"ResourceEventType", xmptype.ResourceEventSoftwareAgent, "AgentNameType", testTextValue, event,
			stringGetter(func(e *xmptype.ResourceEventType) string { return e.SoftwareAgent() }),
			stringSetter(func(e *xmptype.ResourceEventType, v string) error { return e.SetSoftwareAgent(v) })},
		{"ResourceEventType", xmptype.ResourceEventWhen, "DateType", testDateValue, event,
			func(s xmptype.AbstractStructuredType) (any, bool) {
				return s.(*xmptype.ResourceEventType).When()
			},
			func(s xmptype.AbstractStructuredType, v any) error {
				return s.(*xmptype.ResourceEventType).SetWhen(v.(time.Time))
			}},

		// data for ResourceRefType
		{"ResourceRefType", xmptype.ResourceRefDocumentID, "URIType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.DocumentID() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetDocumentID(v) })},
		{"ResourceRefType", xmptype.ResourceRefFilePath, "URIType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.FilePath() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetFilePath(v) })},
		{"ResourceRefType", xmptype.ResourceRefFromPart, "PartType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.FromPart() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetFromPart(v) })},
		{"ResourceRefType", xmptype.ResourceRefInstanceID, "URIType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.InstanceID() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetInstanceID(v) })},
		{"ResourceRefType", xmptype.ResourceRefLastModifyDate, "DateType", testDateValue, ref,
			func(s xmptype.AbstractStructuredType) (any, bool) {
				return s.(*xmptype.ResourceRefType).LastModifyDate()
			},
			func(s xmptype.AbstractStructuredType, v any) error {
				return s.(*xmptype.ResourceRefType).SetLastModifyDate(v.(time.Time))
			}},
		{"ResourceRefType", xmptype.ResourceRefManager, "AgentNameType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.Manager() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetManager(v) })},
		{"ResourceRefType", xmptype.ResourceRefManagerVariant, "TextType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.ManagerVariant() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetManagerVariant(v) })},
		{"ResourceRefType", xmptype.ResourceRefManageTo, "URIType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.ManageTo() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetManageTo(v) })},
		{"ResourceRefType", xmptype.ResourceRefManageUI, "URIType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.ManageUI() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetManageUI(v) })},
		{"ResourceRefType", xmptype.ResourceRefMaskMarkers, "ChoiceType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.MaskMarkers() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetMaskMarkers(v) })},
		{"ResourceRefType", xmptype.ResourceRefPartMapping, "TextType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.PartMapping() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetPartMapping(v) })},
		{"ResourceRefType", xmptype.ResourceRefRenditionClass, "RenditionClassType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.RenditionClass() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetRenditionClass(v) })},
		{"ResourceRefType", xmptype.ResourceRefRenditionParams, "TextType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.RenditionParams() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetRenditionParams(v) })},
		{"ResourceRefType", xmptype.ResourceRefToPart, "PartType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.ToPart() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetToPart(v) })},
		{"ResourceRefType", xmptype.ResourceRefVersionID, "TextType", testTextValue, ref,
			stringGetter(func(r *xmptype.ResourceRefType) string { return r.VersionID() }),
			stringSetter(func(r *xmptype.ResourceRefType, v string) error { return r.SetVersionID(v) })},

		// data for ThumbnailType
		{"ThumbnailType", xmptype.ThumbnailFormat, "ChoiceType", testTextValue, thumbnail,
			stringGetter(func(t *xmptype.ThumbnailType) string { return t.Format() }),
			stringSetter(func(t *xmptype.ThumbnailType, v string) error { return t.SetFormat(v) })},
		{"ThumbnailType", xmptype.ThumbnailHeight, "IntegerType", testIntegerValue, thumbnail,
			func(s xmptype.AbstractStructuredType) (any, bool) {
				return s.(*xmptype.ThumbnailType).Height()
			},
			func(s xmptype.AbstractStructuredType, v any) error {
				return s.(*xmptype.ThumbnailType).SetHeight(v.(int))
			}},
		{"ThumbnailType", xmptype.ThumbnailWidth, "IntegerType", testIntegerValue, thumbnail,
			func(s xmptype.AbstractStructuredType) (any, bool) {
				return s.(*xmptype.ThumbnailType).Width()
			},
			func(s xmptype.AbstractStructuredType, v any) error {
				return s.(*xmptype.ThumbnailType).SetWidth(v.(int))
			}},
		{"ThumbnailType", xmptype.ThumbnailImage, "TextType", testTextValue, thumbnail,
			stringGetter(func(t *xmptype.ThumbnailType) string { return t.Image() }),
			stringSetter(func(t *xmptype.ThumbnailType, v string) error { return t.SetImage(v) })},

		// data for VersionType
		{"VersionType", xmptype.VersionModifier, "ProperNameType", testTextValue, version,
			stringGetter(func(v *xmptype.VersionType) string { return v.Modifier() }),
			stringSetter(func(v *xmptype.VersionType, s string) error { return v.SetModifier(s) })},
	}
}

// TestStructuredInitializedToNull is Java's testInitializedToNull.
func TestStructuredInitializedToNull(t *testing.T) {
	xmp := xmpbox.CreateXMPMetadata()
	for _, row := range structuredRows() {
		structured, _ := row.make(xmp)
		if got := structured.Property(row.fieldName); got != nil {
			t.Errorf("%s.Property(%q) = %v on a fresh value, want nil",
				row.owner, row.fieldName, got)
		}
		// accessor
		if _, found := row.get(structured); found {
			t.Errorf("%s: the accessor of %q found a value on a fresh one, want none",
				row.owner, row.fieldName)
		}
	}
}

// TestStructuredSettingValue is Java's testSettingValue: setting one field
// leaves every other one the type declares unset.
func TestStructuredSettingValue(t *testing.T) {
	xmp := xmpbox.CreateXMPMetadata()
	for _, row := range structuredRows() {
		structured, fields := row.make(xmp)
		if err := row.set(structured, row.value); err != nil {
			t.Fatalf("%s.%s: %v", row.owner, row.fieldName, err)
		}
		if structured.Property(row.fieldName) == nil {
			t.Errorf("%s.Property(%q) = nil after it was set", row.owner, row.fieldName)
		}
		// check other properties not modified
		for _, name := range fields {
			// do not check the current name
			if name == row.fieldName {
				continue
			}
			if got := structured.Property(name); got != nil {
				t.Errorf("%s: setting %q also set %q to %v",
					row.owner, row.fieldName, name, got)
			}
		}
	}
}

// TestStructuredPropertyType is Java's testPropertyType: the stored property is
// of the class the Types constant names.
func TestStructuredPropertyType(t *testing.T) {
	xmp := xmpbox.CreateXMPMetadata()
	for _, row := range structuredRows() {
		structured, _ := row.make(xmp)
		if err := row.set(structured, row.value); err != nil {
			t.Fatalf("%s.%s: %v", row.owner, row.fieldName, err)
		}
		property := structured.Property(row.fieldName)
		if property == nil {
			t.Errorf("%s.Property(%q) = nil after it was set", row.owner, row.fieldName)
			continue
		}
		// check property type
		if got := property.TypeName(); got != row.typeName {
			t.Errorf("%s.%s is a %s, want a %s", row.owner, row.fieldName, got, row.typeName)
		}
	}
}

// TestStructuredSetter is Java's testSetter: the setter stores the value and
// the getter gives it back.
func TestStructuredSetter(t *testing.T) {
	xmp := xmpbox.CreateXMPMetadata()
	for _, row := range structuredRows() {
		structured, _ := row.make(xmp)
		if err := row.set(structured, row.value); err != nil {
			t.Fatalf("%s.%s: %v", row.owner, row.fieldName, err)
		}
		// check property set
		property, isSimple := structured.Property(row.fieldName).(xmptype.AbstractSimpleProperty)
		if !isSimple {
			t.Errorf("%s.%s is not a simple property", row.owner, row.fieldName)
			continue
		}
		if !sameValue(property.Value(), row.value) {
			t.Errorf("%s.%s stored %v, want %v",
				row.owner, row.fieldName, property.Value(), row.value)
		}
		// check getter
		got, found := row.get(structured)
		if !found {
			t.Errorf("%s: the accessor of %q found nothing after it was set",
				row.owner, row.fieldName)
			continue
		}
		if !sameValue(got, row.value) {
			t.Errorf("%s.%s reads back %v, want %v", row.owner, row.fieldName, got, row.value)
		}
	}
}

// sameValue is Java's assertEquals over the three shapes getJavaValue makes.
func sameValue(got, want any) bool {
	if wantTime, isTime := want.(time.Time); isTime {
		gotTime, isTime := got.(time.Time)
		return isTime && gotTime.Equal(wantTime)
	}
	return got == want
}
