<#
.SYNOPSIS
    Regenerates the Java-side inventory that the migration tracking is based on.

.DESCRIPTION
    Walks the Java modules in the repository root, counts the source files and
    lines in each Java package, and writes the result to
    migration/mapping/inventory.tsv. The Go package each Java package maps to
    comes from migration/mapping/packages.tsv; packages missing from that file
    are reported so the mapping can be extended before they are ported.

    Run this after pulling upstream changes, so the porting status is measured
    against the Java tree as it stands rather than as it was.

.EXAMPLE
    pwsh go/migration/scripts/inventory.ps1
#>
[CmdletBinding()]
param(
    # Repository root. Defaults to two levels above this script.
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,

    # Where to write the inventory.
    [string]$OutFile = (Join-Path $PSScriptRoot '..\mapping\inventory.tsv')
)

$ErrorActionPreference = 'Stop'

$modules = @('io', 'fontbox', 'xmpbox', 'pdfbox', 'pdfbox-layout-awt', 'pdfbox-layout-fop', 'tools')

# Load the Java package -> Go package mapping.
$mappingPath = Join-Path $PSScriptRoot '..\mapping\packages.tsv'
$mapping = @{}
if (Test-Path $mappingPath) {
    Get-Content $mappingPath | ForEach-Object {
        if ($_ -match '^\s*#' -or $_.Trim() -eq '') { return }
        $parts = $_ -split "`t"
        if ($parts.Count -ge 2) { $mapping[$parts[0].Trim()] = $parts[1].Trim() }
    }
}

$rows = [System.Collections.Generic.List[object]]::new()
$unmapped = [System.Collections.Generic.List[string]]::new()

foreach ($module in $modules) {
    $srcRoot = Join-Path $RepoRoot "$module\src\main\java"
    if (-not (Test-Path $srcRoot)) {
        Write-Warning "skipping $module : no src/main/java"
        continue
    }

    # Group the .java files by the package directory that contains them.
    Get-ChildItem -Path $srcRoot -Recurse -Filter *.java -File |
        Group-Object { Split-Path $_.FullName -Parent } |
        ForEach-Object {
            $dir = $_.Name
            $javaPackage = $dir.Substring($srcRoot.Length).Trim('\').Replace('\', '.')
            $lines = ($_.Group | ForEach-Object { (Get-Content -LiteralPath $_.FullName | Measure-Object -Line).Lines } |
                Measure-Object -Sum).Sum

            $goPackage = $mapping[$javaPackage]
            if (-not $goPackage) {
                $goPackage = '-'
                $unmapped.Add($javaPackage)
            }

            # A Go package counts as started once its directory holds any .go file.
            $status = 'not-started'
            if ($goPackage -ne '-') {
                $goDir = Join-Path $RepoRoot "go\$($goPackage -replace '/', '\')"
                if ((Test-Path $goDir) -and (Get-ChildItem $goDir -Filter *.go -File -ErrorAction SilentlyContinue)) {
                    $status = 'in-progress'
                }
            }

            $rows.Add([PSCustomObject]@{
                Module      = $module
                JavaPackage = $javaPackage
                JavaFiles   = $_.Group.Count
                JavaLines   = $lines
                GoPackage   = $goPackage
                Status      = $status
            })
        }
}

$sorted = $rows | Sort-Object Module, JavaPackage

$header = "# Generated by migration/scripts/inventory.ps1 -- do not edit by hand.`n" +
          "# Regenerate after pulling upstream Java changes.`n" +
          "module`tjava_package`tjava_files`tjava_lines`tgo_package`tstatus"

$body = $sorted | ForEach-Object {
    "$($_.Module)`t$($_.JavaPackage)`t$($_.JavaFiles)`t$($_.JavaLines)`t$($_.GoPackage)`t$($_.Status)"
}

$outDir = Split-Path $OutFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

# Write UTF-8 without a BOM. Set-Content -Encoding utf8 emits one on Windows
# PowerShell 5.1, and a BOM in a TSV trips up anything parsing the first column.
$resolvedOut = [System.IO.Path]::GetFullPath($OutFile)
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($resolvedOut, [string[]](@($header) + $body), $utf8NoBom)

Write-Host "wrote $($sorted.Count) packages to $OutFile"
Write-Host ("java total: {0} files, {1} lines" -f
    ($sorted | Measure-Object JavaFiles -Sum).Sum,
    ($sorted | Measure-Object JavaLines -Sum).Sum)

if ($unmapped.Count -gt 0) {
    Write-Host ''
    Write-Host "unmapped java packages (add them to mapping/packages.tsv):"
    $unmapped | Sort-Object -Unique | ForEach-Object { Write-Host "  $_" }
}
