// Package bidi is the part of java.text.Bidi that this port needs.
//
// Port of the JDK class, not of anything in PDFBox — it sits beside `go/awt`
// and `go/w3c` for the same reason those do: the Java being migrated uses it,
// and Go has no equivalent.
//
// `golang.org/x/text/unicode/bidi` is not that equivalent, and the port checked
// before writing this. It runs the same algorithm and answers the runs of a
// paragraph, but it hands them back in **logical** order and exposes no
// embedding level at all: `Ordering` has `NumRuns`, `Run` and `Direction`, and
// `Run` has no level. AbstractGlyphLayoutProcessor needs both — the level goes
// to the layout backend, which reads its parity, and the visual order is the
// order the runs are drawn in. Flattening a direction into a level does not
// work either, because `reorderVisually` is defined over the numbers: the
// running Java answers level 2 for an LTR run inside an RTL paragraph, and
// reordering [1 0 1] does not give what reordering [1 2 1] gives.
//
// What this package does take from `x/text` is the character data —
// `bidi.LookupRune(r).Class()` — which is the Unicode BidiClass property and is
// exported. The algorithm on top of it is UAX#9, written here.
//
// **This is a substitution, and it is measured.** `bidi_test.go` holds a corpus
// generated by driving the running Java through
// AbstractGlyphLayoutProcessor.doBidiSplittingAndReordering; every wanted value
// there is Java's.
package bidi

import (
	"unicode/utf16"

	xbidi "golang.org/x/text/unicode/bidi"
)

// The two direction constants java.text.Bidi declares that this port uses.
const (
	// DirectionLeftToRight is Bidi.DIRECTION_LEFT_TO_RIGHT.
	DirectionLeftToRight = 0

	// DirectionRightToLeft is Bidi.DIRECTION_RIGHT_TO_LEFT.
	DirectionRightToLeft = 1

	// DirectionDefaultLeftToRight is Bidi.DIRECTION_DEFAULT_LEFT_TO_RIGHT: the
	// paragraph level comes from the first strong character, and is 0 where
	// there is none.
	DirectionDefaultLeftToRight = -2

	// DirectionDefaultRightToLeft is Bidi.DIRECTION_DEFAULT_RIGHT_TO_LEFT.
	DirectionDefaultRightToLeft = -1
)

// maxDepth is UAX#9's max_depth: the deepest explicit embedding.
const maxDepth = 125

// RequiresBidi reports whether the text needs the bidirectional algorithm at
// all.
//
// Port of the static Bidi.requiresBidi(char[], int, int), which answers true
// where some character is strongly right to left, is an Arabic number, or is an
// explicit formatting control.
//
// An Arabic-Indic number does count, which the corpus settles: Latin text
// followed by Arabic-Indic digits comes back from the running Java as two runs
// at levels 0 and 2, so the analysis ran. That the same digits *alone* answer
// one run at level 0 is a different rule -- the caller asks isMixed first, and
// an unmixed paragraph answers getBaseLevel rather than the run's own level.
func RequiresBidi(units []uint16) bool {
	for i := 0; i < len(units); i++ {
		r, size := decodeUnits(units[i:])
		i += size - 1
		switch classOf(r) {
		case xbidi.R, xbidi.AL, xbidi.AN, xbidi.RLE, xbidi.RLO, xbidi.LRE, xbidi.LRO,
			xbidi.PDF, xbidi.RLI, xbidi.LRI, xbidi.FSI, xbidi.PDI:
			return true
		}
	}
	return false
}

// Run is one level run of a paragraph: where it starts and ends in the text,
// and the embedding level it resolved to.
type Run struct {
	// Start and Limit are indices into the UTF-16 units of the paragraph.
	Start, Limit int

	// Level is the resolved embedding level. Even is left to right.
	Level int
}

// Paragraph is the analysis of one paragraph of text.
//
// Port of the java.text.Bidi object, which is built over a paragraph and then
// asked for its runs.
type Paragraph struct {
	// units is the text, in UTF-16, because every index java.text.Bidi answers
	// is a UTF-16 index.
	units []uint16

	// levels is the resolved level of each unit.
	levels []int

	// paragraphLevel is the level rules P2 and P3 gave the paragraph.
	paragraphLevel int

	runs []Run
}

// NewParagraph analyses the given text at the given flags, which is
// `new Bidi(String, int)`.
func NewParagraph(text string, flags int) *Paragraph {
	p := &Paragraph{units: utf16.Encode([]rune(text))}
	p.resolve(flags)
	return p
}

// BaseLevel is Bidi.getBaseLevel().
func (p *Paragraph) BaseLevel() int { return p.paragraphLevel }

// IsMixed is Bidi.isMixed(): the paragraph has runs of more than one level.
func (p *Paragraph) IsMixed() bool { return len(p.runs) > 1 }

// RunCount is Bidi.getRunCount().
func (p *Paragraph) RunCount() int { return len(p.runs) }

// RunLevel is Bidi.getRunLevel(int).
func (p *Paragraph) RunLevel(i int) int { return p.runs[i].Level }

// RunStart is Bidi.getRunStart(int), a UTF-16 index.
func (p *Paragraph) RunStart(i int) int { return p.runs[i].Start }

// RunLimit is Bidi.getRunLimit(int), a UTF-16 index.
func (p *Paragraph) RunLimit(i int) int { return p.runs[i].Limit }

// Text returns the paragraph's text between two UTF-16 indices, which is what
// String.substring answers for the same pair.
func (p *Paragraph) Text(start, limit int) string {
	return string(utf16.Decode(p.units[start:limit]))
}

// ReorderVisually puts the objects into visual order, given the level of each.
//
// Port of the static Bidi.reorderVisually(byte[], int, Object[], int, int),
// which is rule L2: from the highest level down to the lowest odd level,
// reverse every maximal run of objects at that level or above.
func ReorderVisually(levels []int, objects []int) {
	if len(levels) == 0 {
		return
	}
	highest := 0
	lowestOdd := maxDepth + 2
	for _, level := range levels {
		if level > highest {
			highest = level
		}
		if level%2 != 0 && level < lowestOdd {
			lowestOdd = level
		}
	}
	for level := highest; level >= lowestOdd; level-- {
		for i := 0; i < len(levels); i++ {
			if levels[i] < level {
				continue
			}
			// find the end of this maximal run
			start := i
			for i < len(levels) && levels[i] >= level {
				i++
			}
			for left, right := start, i-1; left < right; left, right = left+1, right-1 {
				objects[left], objects[right] = objects[right], objects[left]
			}
		}
	}
}

// classOf answers the Unicode BidiClass of a rune, which is the one piece of
// character data this package takes from x/text.
func classOf(r rune) xbidi.Class {
	properties, _ := xbidi.LookupRune(r)
	return properties.Class()
}

// decodeUnits reads one rune from the front of a UTF-16 slice, answering it and
// how many units it took. An unpaired surrogate answers itself, which is what
// Java's char-at-a-time walk sees.
func decodeUnits(units []uint16) (rune, int) {
	if len(units) >= 2 && utf16.IsSurrogate(rune(units[0])) {
		if r := utf16.DecodeRune(rune(units[0]), rune(units[1])); r != 0xFFFD {
			return r, 2
		}
	}
	return rune(units[0]), 1
}
