package ttf

// unicodeScriptToOpenTypeTag associates Unicode scripts with one or more
// OpenType script tags. Script tags are not necessarily the same as Unicode
// scripts. A single Unicode script may correspond to multiple tags, especially
// when there has been a revision to the latter (e.g. Bengali -> [bng2, beng]).
// When there are multiple tags, they are ordered from newest to oldest.
//
// See https://www.microsoft.com/typography/otspec/scripttags.htm
//
// Port of the map of the same name in org.apache.fontbox.ttf.OpenTypeScript.
var unicodeScriptToOpenTypeTag = map[string][]string{
	"Adlam":                  {"adlm"},
	"Ahom":                   {"ahom"},
	"Anatolian_Hieroglyphs":  {"hluw"},
	"Arabic":                 {"arab"},
	"Armenian":               {"armn"},
	"Avestan":                {"avst"},
	"Balinese":               {"bali"},
	"Bamum":                  {"bamu"},
	"Bassa_Vah":              {"bass"},
	"Batak":                  {"batk"},
	"Bengali":                {"bng2", "beng"},
	"Bhaiksuki":              {"bhks"},
	"Bopomofo":               {"bopo"},
	"Brahmi":                 {"brah"},
	"Braille":                {"brai"},
	"Buginese":               {"bugi"},
	"Buhid":                  {"buhd"},
	"Canadian_Aboriginal":    {"cans"},
	"Carian":                 {"cari"},
	"Caucasian_Albanian":     {"aghb"},
	"Chakma":                 {"cakm"},
	"Cham":                   {"cham"},
	"Cherokee":               {"cher"},
	"Common":                 {"DFLT"},
	"Coptic":                 {"copt"},
	"Cuneiform":              {"xsux"},
	"Cypriot":                {"cprt"},
	"Cyrillic":               {"cyrl"},
	"Deseret":                {"dsrt"},
	"Devanagari":             {"dev2", "deva"},
	"Duployan":               {"dupl"},
	"Egyptian_Hieroglyphs":   {"egyp"},
	"Elbasan":                {"elba"},
	"Ethiopic":               {"ethi"},
	"Georgian":               {"geor"},
	"Glagolitic":             {"glag"},
	"Gothic":                 {"goth"},
	"Grantha":                {"gran"},
	"Greek":                  {"grek"},
	"Gujarati":               {"gjr2", "gujr"},
	"Gurmukhi":               {"gur2", "guru"},
	"Han":                    {"hani"},
	"Hangul":                 {"hang"},
	"Hanunoo":                {"hano"},
	"Hatran":                 {"hatr"},
	"Hebrew":                 {"hebr"},
	"Hiragana":               {"kana"},
	"Imperial_Aramaic":       {"armi"},
	"Inherited":              {"Inherited"},
	"Inscriptional_Pahlavi":  {"phli"},
	"Inscriptional_Parthian": {"prti"},
	"Javanese":               {"java"},
	"Kaithi":                 {"kthi"},
	"Kannada":                {"knd2", "knda"},
	"Katakana":               {"kana"},
	"Kayah_Li":               {"kali"},
	"Kharoshthi":             {"khar"},
	"Khmer":                  {"khmr"},
	"Khojki":                 {"khoj"},
	"Khudawadi":              {"sind"},
	"Lao":                    {"lao "},
	"Latin":                  {"latn"},
	"Lepcha":                 {"lepc"},
	"Limbu":                  {"limb"},
	"Linear_A":               {"lina"},
	"Linear_B":               {"linb"},
	"Lisu":                   {"lisu"},
	"Lycian":                 {"lyci"},
	"Lydian":                 {"lydi"},
	"Mahajani":               {"mahj"},
	"Malayalam":              {"mlm2", "mlym"},
	"Mandaic":                {"mand"},
	"Manichaean":             {"mani"},
	"Marchen":                {"marc"},
	"Meetei_Mayek":           {"mtei"},
	"Mende_Kikakui":          {"mend"},
	"Meroitic_Cursive":       {"merc"},
	"Meroitic_Hieroglyphs":   {"mero"},
	"Miao":                   {"plrd"},
	"Modi":                   {"modi"},
	"Mongolian":              {"mong"},
	"Mro":                    {"mroo"},
	"Multani":                {"mult"},
	"Myanmar":                {"mym2", "mymr"},
	"Nabataean":              {"nbat"},
	"Newa":                   {"newa"},
	"New_Tai_Lue":            {"talu"},
	"Nko":                    {"nko "},
	"Ogham":                  {"ogam"},
	"Ol_Chiki":               {"olck"},
	"Old_Italic":             {"ital"},
	"Old_Hungarian":          {"hung"},
	"Old_North_Arabian":      {"narb"},
	"Old_Permic":             {"perm"},
	"Old_Persian":            {"xpeo"},
	"Old_South_Arabian":      {"sarb"},
	"Old_Turkic":             {"orkh"},
	"Oriya":                  {"ory2", "orya"},
	"Osage":                  {"osge"},
	"Osmanya":                {"osma"},
	"Pahawh_Hmong":           {"hmng"},
	"Palmyrene":              {"palm"},
	"Pau_Cin_Hau":            {"pauc"},
	"Phags_Pa":               {"phag"},
	"Phoenician":             {"phnx"},
	"Psalter_Pahlavi":        {"phlp"},
	"Rejang":                 {"rjng"},
	"Runic":                  {"runr"},
	"Samaritan":              {"samr"},
	"Saurashtra":             {"saur"},
	"Sharada":                {"shrd"},
	"Shavian":                {"shaw"},
	"Siddham":                {"sidd"},
	"SignWriting":            {"sgnw"},
	"Sinhala":                {"sinh"},
	"Sora_Sompeng":           {"sora"},
	"Sundanese":              {"sund"},
	"Syloti_Nagri":           {"sylo"},
	"Syriac":                 {"syrc"},
	"Tagalog":                {"tglg"},
	"Tagbanwa":               {"tagb"},
	"Tai_Le":                 {"tale"},
	"Tai_Tham":               {"lana"},
	"Tai_Viet":               {"tavt"},
	"Takri":                  {"takr"},
	"Tamil":                  {"tml2", "taml"},
	"Tangut":                 {"tang"},
	"Telugu":                 {"tel2", "telu"},
	"Thaana":                 {"thaa"},
	"Thai":                   {"thai"},
	"Tibetan":                {"tibt"},
	"Tifinagh":               {"tfng"},
	"Tirhuta":                {"tirh"},
	"Ugaritic":               {"ugar"},
	"Unknown":                {"DFLT"},
	"Vai":                    {"vai "},
	"Warang_Citi":            {"wara"},
	"Yi":                     {"yi  "},
}
