package annotation_test

// Ported from
// pdfbox/src/test/java/org/apache/pdfbox/pdmodel/interactive/annotation/AppearanceGenerationTest.java.
//
// Tests the appearance generation for annotations generated using Adobe Reader
// DC.
//
//   - gets the annotation
//   - gets the appearance stream and it's tokens
//   - removes the appearance stream
//   - regenerates the appearance
//   - compares the tokens from the original to the ones created by PDFBox
//
// For the initial work only the token operators are compared to ensure the same
// basic operation. Upon refinement the operators parameters could also be
// verified.
//
// renderTest and testAnnotationAppearancesGeneration are not here: both render
// the page and compare images, and rendering is a later slice. See
// migration/STATUS.md.

import (
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/shinguakira/pdfbox-go/go/pdfbox"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/contentstream/operator"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/cos"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/pdfparser"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/pdmodel"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/pdmodel/common"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/pdmodel/font"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/pdmodel/interactive/annotation"
	"github.com/shinguakira/pdfbox-go/go/pdfbox/pdmodel/interactive/form"
)

// appearanceDelta is the DELTA of AppearanceGenerationTest: a difference in
// float values smaller than this will be treated equal between Adobe and PDFBox
// values.
//
// TODO: revisit that number as our code improves
const appearanceDelta = 3e-3

// nameOfAnnotationTypesPDF is the NAME_OF_PDF of AppearanceGenerationTest.
const nameOfAnnotationTypesPDF = "AnnotationTypes.pdf"

// TestRectangleFullStrokeNoFill is
// AppearanceGenerationTest.rectangleFullStrokeNoFill. The test is incomplete as
// the content stream differs.
func TestRectangleFullStrokeNoFill(t *testing.T) {
	document, err := pdfbox.LoadPDF(inDir + nameOfAnnotationTypesPDF)
	if err != nil {
		t.Fatal(err)
	}
	defer document.Close()

	page := document.Page(0)
	annotations := page.Annotations().ToSlice()

	// can't do 14 and 16 (clouds, by our own algorithm)
	// odd annotations are popups
	for _, index := range []int{0, 2, 4, 6, 8, 10, 12, 18, 20, 24, 26, 28, 30, 32, 34} {
		checkAnnotationTokens(t, index, annotations[index])
	}

	// Save the file for manual comparison for now
	file := filepath.Join(t.TempDir(), nameOfAnnotationTypesPDF+"-newAP.pdf")
	out, err := os.Create(file)
	if err != nil {
		t.Fatal(err)
	}
	defer out.Close()
	if err := document.Save(out); err != nil {
		t.Fatal(err)
	}
}

// checkAnnotationTokens is the private checkAnnotationTokens of the Java test.
func checkAnnotationTokens(t *testing.T, index int, annot annotation.PDAnnotation) {
	t.Helper()
	// get the tokens of the content stream generated by Adobe
	tokensForOriginal := parseAppearance(t, annot.NormalAppearanceStream())

	// get the tokens for the content stream generated by PDFBox
	annot.AnnotationDictionary().RemoveItem(cos.AP)
	if err := annot.ConstructAppearances(); err != nil {
		t.Fatalf("annotation %d: %v", index, err)
	}
	tokensForPdfbox := parseAppearance(t, annot.NormalAppearanceStream())

	if len(tokensForOriginal) != len(tokensForPdfbox) {
		t.Fatalf("annotation %d: the number of tokens in the content stream should be the "+
			"same: %d, got %d", index, len(tokensForOriginal), len(tokensForPdfbox))
	}
	for actualToken, tokenForOriginal := range tokensForOriginal {
		tokenForPdfbox := tokensForPdfbox[actualToken]
		if got, want := typeName(tokenForPdfbox), typeName(tokenForOriginal); got != want {
			t.Errorf("annotation %d token %d: the tokens should have the same type: "+
				"%s, got %s", index, actualToken, want, got)
			continue
		}
		switch original := tokenForOriginal.(type) {
		case *operator.Operator:
			if got, want := tokenForPdfbox.(*operator.Operator).Name(),
				original.Name(); got != want {
				t.Errorf("annotation %d token %d: the operator generated by PDFBox should "+
					"be the same Operator: %s, got %s", index, actualToken, want, got)
			}
		case *cos.Float:
			got := tokenForPdfbox.(*cos.Float).FloatValue()
			if math.Abs(float64(original.FloatValue()-got)) >= appearanceDelta {
				t.Errorf("annotation %d token %d: the difference between the numbers should "+
					"be smaller than %v: %v against %v",
					index, actualToken, float32(appearanceDelta), original.FloatValue(), got)
			}
		}
	}
}

// parseAppearance reads the tokens of the given appearance stream.
func parseAppearance(t *testing.T, appearanceStream *annotation.PDAppearanceStream) []any {
	t.Helper()
	content, err := appearanceStream.ContentsForRandomAccess()
	if err != nil {
		t.Fatal(err)
	}
	parser, err := pdfparser.NewStreamTokenParserSource(content)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := parser.Parse()
	if err != nil {
		t.Fatal(err)
	}
	return tokens
}

// typeName is Object.getClass().getName(), which the Java test compares.
func typeName(token any) string {
	switch token.(type) {
	case *operator.Operator:
		return "Operator"
	case *cos.Float:
		return "COSFloat"
	case *cos.Integer:
		return "COSInteger"
	case *cos.Name:
		return "COSName"
	case *cos.StringObj:
		return "COSString"
	case *cos.Array:
		return "COSArray"
	case *cos.Dictionary:
		return "COSDictionary"
	case *cos.Boolean:
		return "COSBoolean"
	}
	return "unknown"
}

// TestTinyHorizontalFieldWith0FontSize is
// AppearanceGenerationTest.testTinyHorizontalFieldWith0FontSize.
func TestTinyHorizontalFieldWith0FontSize(t *testing.T) {
	// Create a new document with an empty page.
	document := pdmodel.NewPDDocument()
	defer document.Close()
	page := pdmodel.NewPDPageOfSize(common.A4)
	document.AddPage(page)
	helvetica, err := font.NewPDType1FontStandard14(font.Helvetica)
	if err != nil {
		t.Fatal(err)
	}
	resources := pdmodel.NewPDResources()
	resources.PutFont(cos.Helv, helvetica)
	acroForm := form.NewPDAcroForm(document)
	form.SetAcroFormOfCatalog(document.DocumentCatalog(), acroForm)
	acroForm.SetDefaultResources(resources)
	const defaultAppearanceString = "/Helv 0 Tf 0 g"
	acroForm.SetDefaultAppearance(defaultAppearanceString)
	textBox := form.NewPDTextField(acroForm)
	textBox.SetPartialName("SampleField")
	textBox.SetDefaultAppearance(defaultAppearanceString)
	acroForm.SetFields(append(acroForm.Fields(), textBox))
	widget := textBox.Widgets()[0]
	rect := common.NewPDRectangleOf(50, 750, 1, 50)
	widget.SetRectangle(rect)
	widget.SetPage(page)
	page.Annotations().Add(widget)
	if err := textBox.SetValue(""); err != nil { // mayhem happened here
		t.Fatal(err)
	}
}
